187 days ago <- my algo for the day!!
186 days ago <- my algo for the day!!
185 days ago <- my algo for the day!!
184 days ago <- my algo for the day!!
183 days ago <- my algo for the day!!
182 days ago <- my algo for the day!!
181 days ago <- my algo for the day!!
180 days ago <- my algo for the day!!
179 days ago <- my algo for the day!!
178 days ago <- my algo for the day!!
177 days ago <- my algo for the day!!
176 days ago <- my algo for the day!!
175 days ago <- my algo for the day!!
174 days ago <- my algo for the day!!
173 days ago <- my algo for the day!!
172 days ago <- my algo for the day!!
171 days ago <- my algo for the day!!
170 days ago <- my algo for the day!!
169 days ago <- my algo for the day!!
168 days ago <- my algo for the day!!
167 days ago <- my algo for the day!!
166 days ago <- my algo for the day!!
165 days ago <- my algo for the day!!
164 days ago <- my algo for the day!!
163 days ago <- my algo for the day!!
162 days ago <- my algo for the day!!
161 days ago <- my algo for the day!!
160 days ago <- my algo for the day!!
159 days ago <- my algo for the day!!
158 days ago <- my algo for the day!!
157 days ago <- my algo for the day!!
156 days ago <- my algo for the day!!
155 days ago <- my algo for the day!!
154 days ago <- my algo for the day!!
153 days ago <- my algo for the day!!
152 days ago <- my algo for the day!!
151 days ago <- my algo for the day!!
187 days ago <- my algo for the day!!
186 days ago <- my algo for the day!!
185 days ago <- my algo for the day!!
184 days ago <- my algo for the day!!
183 days ago <- my algo for the day!!
182 days ago <- my algo for the day!!
181 days ago <- my algo for the day!!
180 days ago <- my algo for the day!!
179 days ago <- my algo for the day!!
178 days ago <- my algo for the day!!
177 days ago <- my algo for the day!!
176 days ago <- my algo for the day!!
175 days ago <- my algo for the day!!
174 days ago <- my algo for the day!!
173 days ago <- my algo for the day!!
172 days ago <- my algo for the day!!
171 days ago <- my algo for the day!!
170 days ago <- my algo for the day!!
169 days ago <- my algo for the day!!
168 days ago <- my algo for the day!!
167 days ago <- my algo for the day!!
166 days ago <- my algo for the day!!
165 days ago <- my algo for the day!!
164 days ago <- my algo for the day!!
163 days ago <- my algo for the day!!
162 days ago <- my algo for the day!!
161 days ago <- my algo for the day!!
160 days ago <- my algo for the day!!
